regulations sayfaları
whatshafiz/whatshafiz-frontend pull request #48
Opened 2023-03-25 21:46 UTC by saidtaylan

2023-03-26 12:24 UTC, nozkok requested changes

2023-03-26 12:24 UTC, nozkok commented on src/router/index.ts
> +        path: "/regulations/:slug/update",
bunu update yerine edit yapalım.
yukarda bende profile için olanı edit yapmışım, onun gibi. 

![image](https://user-images.githubusercontent.com/6912824/227774159-46dc2f2b-5c1e-4a40-bf76-2262302f38f2.png)

2023-03-26 12:24 UTC, nozkok commented on src/pages/regulations/View.vue
> +</template>
bu dosya sonlarına boş satırları atlamayalım
burada uyarı vermesin

2023-03-26 12:24 UTC, nozkok commented on src/pages/regulations/List.vue
> +import Lucide from "@/base-components/Lucide/Lucide.vue";
liste için mobil görünümde şöyle bir problemimiz var.

![image](https://user-images.githubusercontent.com/6912824/227774449-03f1c1f6-c9b7-45ef-828d-4aeaba464a82.png)

2023-03-26 12:24 UTC, nozkok commented on src/pages/regulations/List.vue
> +    <div class="h-screen">
bu  tablo ve formları  card içine koysak çok daha güzel olacak.

http://enigma-vue.left4code.com/regular-table

bak mesela burada her bir  tabloyu ayrı ayrı card içine koymuşlar.
bizimde  layout içinde tüm içerik böyle bir card içinde olabilir
aynı yapıyı profil  sayfalarındada görebilirsin.
Özellikle edit sayfasında o anda hangi içeriği editlediğini bilmiyor kullanıcı
hangi yönetmeliği düzenliyor sayfada hiçbir bilgi yok.
card yaptığında  başlığına  o an hangi  yönetmeliği düzenliyorsa bununla ilgili bilgi yazılır

Ayrıca  yine profil ve login sayfalarında görebileceğin gibi
kaydete bastığında   butonu  disable edip  yükleniyor ikonu çıkarıyorum
bu şunun için önemli server biraz geç cevap verdiğinde peş peşe tıklamaları engellemiş oluyoruz.
ve kullanıcı yaptığı aksiyonun alındığını anlıyor.
özellikle mobilde  dokunamadımmı acaba duygusunun önüne geçiyor

2023-03-26 12:24 UTC, nozkok commented on src/pages/regulations/List.vue
> +                                    <Lucide icon="Edit" class="w-4 h-4 mr-2" /> Düzenle
Burada düzenleme yetkisi yoksa kullanıcıya düzenle  metinli bir buton göstermek doğru değil.
burada iki buton olsun görüntüle ve  düzenle

düzenle sadece yetkisi olanlarda çıksın
düzenleme yetkisi olanda sadece görüntüleyebilsin.

2023-03-26 12:24 UTC, nozkok commented on src/stores/regulations.ts
> +                throw error
bu try catchler şu haliyle hiç bir işe yaramıyor

2023-03-26 12:24 UTC, nozkok commented on src/stores/regulations.ts
> +
boş satır silelim

2023-03-26 12:24 UTC, nozkok commented on src/pages/regulations/List.vue
> +
boş satır silelim

2023-03-26 12:24 UTC, nozkok commented on src/pages/regulations/List.vue
> +                    <Tr>
şu indentler temada varsayılan 2 boşluk ileydi
ama senin ide sanırım tab tab atıyor
bunları tutarlı hale getirelim

2023-03-30 14:47 UTC, mucan54 commented on src/stores/regulations.ts
> +export const useRegulationsStore = defineStore('regulations', {
Burda tekil isim kullanılmış https://github.com/whatshafiz/whatshafiz-frontend/blob/736e964fc0932a31e8e90986da676ac28a9e910c/src/stores/course.ts#L5 

`export const useCourseStore = defineStore('course', {`

@nozkok

2023-03-30 14:58 UTC, nozkok commented on src/stores/regulations.ts
> +export const useRegulationsStore = defineStore('regulations', {
Doğru tekil olması lazım

2023-04-05 07:38 UTC, nozkok approved these changes

2023-04-05 07:38 UTC, merged